### ISSUE TITLE
Librarie update

### ISSUE THREAD

**Issue by steve-1000** [matgrhn/honigautomat#1]
Möchte den Code gerne auf einem Arduino Nano every nutzen - sollte sogar voll kompatibel sein?!
folgend Vorschläge hätte ich:

aufgrund von Fehlermeldungen beim kompilieren:
die Librarie LCD.h war nicht out of the Box in meiner Arduino ide Vers. 1.8.19 verfügbar.
Konnte diese dann hier runterladen:https://github.com/jenschr/Arduino-libraries/tree/master/LiquidCrystal
und manuell in "C:\Program Files (x86)\Arduino\libraries" (Windows10) hinzufügen.
evtl. gibt es da was aktuelleres was diese manuelle Anpassung überflüssig macht?

Punkt 2: in der lcd.h Librarie wird noch die "#include "WProgram.h" verwendet - > ebenfalls nicht mehr aktuell. Die manuellen notwendigen Anpassungen hab ich hier gefunden: 
https://forum.arduino.cc/t/wprogram-h-problem-help/499019/4
#include "WProgram.h --> soll demnach in #include <Arduino.h> geändert werden.

Ansonsten: Top Thema und Projekt! Danke fürs teilen!!

**Comment by matgrhn** [comment]
Hallo Joshuad,
stimmt, du brauchst die Bibliothek für das LCD Display, z.B. https://www.dropbox.com/s/h7psvzjazhsivgu/newLiquidCrystal.zip?dl=0

diejenige, die du genannt hast, mag auch funktionieren.
Viele Grüße 
Matthias
